### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by hwittenborn** [FauxFaux/apt-pkg-native-rs#8]
Hi! I was curious if this was still maintained, and if it wasn't I was wondering if you'd want to link in the README to the [`rust-apt` crate](https://crates.io/crates/rust-apt), which is being worked on by me and this other guy (mostly credits to the other guy, I'm a fairly addition to the project).

**Comment by FauxFaux** [comment]
I am not currently using this crate, but was planning on keeping it working. I'll add a link.
